### ISSUE TITLE
Globbing for JS partials

### ISSUE THREAD

**Issue by davetgreen** [mkdo/kapow-grunt#16]
It would save time if we could add JS partials into the `assets/js/parts` folder that would be automatically picked up and included by the Grunt tasks. This way, dropping in a JS partial for something such as Google maps would be quick and painless, and wouldn't require altering the `gruntfile` and rebuilding the assets.

As a naming convention, perhaps anything with an underscore prefix would be automatically included in the footer, whereas any file that does not have an underscore has to be manually added to the concatenation lists in the `gruntfile` for the header or footer.

@mwtsn penny for your thoughts on this.

**Comment by mwtsn** [comment]
Hmmm, could be tricky @davetgreen how would you differentiate between admin and front-end partials? I personally like the control, but good idea in principle.

**Comment by davetgreen** [comment]
@mwtsn I suppose the easiest win would be to adopt a naming convention like...

`a_partial-name.js`
`f_partial-name-.js`
`h_partial-name.js`

Or use a suffix instead...

**Comment by mwtsn** [comment]
@davetgreen yeah, that would work, or something like that anyway.

**Comment by davetgreen** [comment]
Note to self, worth auto including library partials as well?

**Comment by davetgreen** [comment]
Completed. Support for auto-inclusion of header and footer libraries and partials is now in place: files with a suffix of `_h.js` or `_f.js` will be automatically linted/concatenated/uglified without having to manually add them to the `gruntfile.js`.
