### ISSUE TITLE
grunt-sass-lint

### ISSUE THREAD

**Issue by davetgreen** [mkdo/kapow-grunt#6]
grunt-scss-lint is no longer updated and is significantly slower than the new grunt-sass-lint.

However, having tested grunt-sass-lint there is currently an issue with interpolated strings that causes a fatal error. Until this has been resolved we cannot use it in Kapow!

The source of the issue is in gonzales-pe which is a dependency of sass-lint, which in turn is a dependency of grunt-sass-lint. 

I raised an issue [here](https://github.com/sasstools/sass-lint/issues/184), and was referred to [this issue](https://github.com/tonyganch/gonzales-pe/issues/115#issuecomment-149358821) which I'm watching.

As soon as string interpolation is fixed, we're good to go!

**Comment by czebe** [comment]
This is a crucial error. Any news on this, ETA of fix (days/months)?

**Comment by davetgreen** [comment]
@czebe I'm tracking their progress at the moment. As soon as it's updated and I've tested the build locally I'll be introducing grunt-sass-lint into Kapow! asap! :)

**Comment by czebe** [comment]
Much appreciated! We're sitting on the edge of our seats here.

**Comment by davetgreen** [comment]
This was resolved several months ago. Closing.
