### ISSUE TITLE
Grunt assets/fonts sync

### ISSUE THREAD

**Issue by nervewax** [mkdo/kapow-grunt#8]
Grunt syncs fonts placed in:
`assets/fonts`
to
`assets/fonts/assets/fonts`

<img width="185" alt="screen shot 2017-05-10 at 13 48 00" src="https://cloud.githubusercontent.com/assets/7255911/25899334/64eadfda-3587-11e7-935a-5967fd39a610.png">

**Comment by davetgreen** [comment]
@nervewax Ahh yeah, I fixed this on GFS or Innova but never patched it into Kapow!. I'll check your PR out in a bit and will merge. 🎉

**Comment by davetgreen** [comment]
@nervewax merged and closing. Same fix I applied in GFS 👌
